### ISSUE TITLE
报错，怎么解决？

### ISSUE THREAD

**Issue by jiaying96** [17mon/java#19]
Exception in thread "main" java.nio.BufferUnderflowException
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:191)
	at com.ip.IPExt.load(IPExt.java:107)
	at com.ip.IPExt.load(IPExt.java:34)
	at com.ip.IPExt.main(IPExt.java:15)

**Comment by Duangit** [comment]
这个怎么解决，在本地是正常的，在spark集群回报这个错 @17mon

**Comment by Duangit** [comment]
已解决

**Comment by lephix** [comment]
我也报错，IPExt读取最新的datx文件。

    Caused by: java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
        at xxxx.IPExt.load(IPExt.java:111)

发现datx的文件大小是2556547，但是读出来第一个int是2783363，超过了文件大小了。

**Comment by senlizishi** [comment]
> 已解决

请问是如何解决的？我也遇到了这个问题
