### ISSUE TITLE
IndexOutOfBoundsException in IPExt test

### ISSUE THREAD

**Issue by yiming187** [17mon/java#6]
I just downloaded the source code and data file. The IP.java runs very well, but the IPExt.java met some errors. Do you have any idea?

	public static void main(String[] args) {
		IPExt.load("data/17monipdb.dat");

		System.out.println(Arrays.toString(IPExt.find("8.8.8.8")));
		System.out.println(Arrays.toString(IPExt.find("118.28.8.8")));
		System.out.println(Arrays.toString(IPExt.find("255.255.255.255")));
	}
``
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:365)
	at com.yiming187.jnetpcap_example.ip.IPExt.find(IPExt.java:66)
	at com.yiming187.jnetpcap_example.ip.IPExt.main(IPExt.java:18)``

**Comment by pangee** [comment]
me too ...

**Comment by 17mon** [comment]
IPExt 只支持datx格式的文件不支持dat格式

**Comment by childe** [comment]
@17mon  就是下载的datx文件, 也报错.

**Comment by sagomilk** [comment]
me too ...
