### ISSUE TITLE
something wrong with your code.

### ISSUE THREAD

**Issue by CasperMXP** [17mon/java#7]
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.HeapByteBuffer.getInt(Unknown Source)
	at org.casper.iptest.IPExt.find(IPExt.java:66)
	at org.casper.iptest.IPExt.main(IPExt.java:18)

**Comment by 17mon** [comment]
请问你 Load的数据库格式是哪个？ IPExt代码只支持 datx 格式
